/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MotosikletlerIndexRouteImport } from './routes/motosikletler/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MotosikletlerIndexRoute = MotosikletlerIndexRouteImport.update({
  id: '/motosikletler/',
  path: '/motosikletler/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/motosikletler/': typeof MotosikletlerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/motosikletler': typeof MotosikletlerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/motosikletler/': typeof MotosikletlerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/motosikletler/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/motosikletler'
  id: '__root__' | '/' | '/motosikletler/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MotosikletlerIndexRoute: typeof MotosikletlerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motosikletler/': {
      id: '/motosikletler/'
      path: '/motosikletler'
      fullPath: '/motosikletler/'
      preLoaderRoute: typeof MotosikletlerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MotosikletlerIndexRoute: MotosikletlerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
